name: Docker Build and Push

# è§¦å‘æ¡ä»¶ï¼šæŽ¨é€åˆ°ä¸»åˆ†æ”¯æˆ–æ‰‹åŠ¨è§¦å‘
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag_suffix:
        description: 'Additional tag suffix (optional)'
        required: false
        type: string

# çŽ¯å¢ƒå˜é‡
env:
  REGISTRY: docker.io
  # éœ€è¦åœ¨GitHub Secretsä¸­è®¾ç½® DOCKER_USERNAME
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/your-app-name

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # æ£€å‡ºä»£ç 
      - name: Checkout code
        uses: actions/checkout@v4

      # è®¾ç½®Docker Buildxï¼ˆæ”¯æŒå¤šæž¶æž„æž„å»ºï¼‰
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          platforms: linux/amd64,linux/arm64

      # ç™»å½•Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # æå–é•œåƒå…ƒæ•°æ®å’Œæ ‡ç­¾
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # åŸºäºŽåˆ†æ”¯çš„æ ‡ç­¾
            type=ref,event=branch
            # åŸºäºŽSHAçš„æ ‡ç­¾
            type=sha,prefix={{branch}}-,format=short
            # mainåˆ†æ”¯çš„latestæ ‡ç­¾
            type=raw,value=latest,enable={{is_default_branch}}
            # ç”Ÿäº§æ—¶é—´æˆ³æ ‡ç­¾
            type=raw,value=prod-{{date 'YYYYMMDD-HHmmss'}},enable={{is_default_branch}}
            # è‡ªå®šä¹‰åŽç¼€æ ‡ç­¾ï¼ˆå¦‚æžœæä¾›ï¼‰
            type=raw,value={{branch}}${{ inputs.tag_suffix && format('-{0}', inputs.tag_suffix) || '' }},enable=${{ inputs.tag_suffix != '' }}
          labels: |
            org.opencontainers.image.title=Your App Name
            org.opencontainers.image.description=Node.js Express API application
            org.opencontainers.image.vendor=Your Name
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}

      # æž„å»ºå¹¶æŽ¨é€Dockeré•œåƒ
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            BUILD_DATE={{date 'YYYY-MM-DDTHH:mm:ssZ'}}
            GIT_SHA=${{ github.sha }}
            GIT_REF=${{ github.ref_name }}

      # ç”Ÿæˆæž„å»ºæ‘˜è¦
      - name: Generate build summary
        if: success()
        run: |
          echo "## Docker Build Summary ðŸ³" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Published Image" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Tags Published" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.meta.outputs.tags }}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Date:** $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_STEP_SUMMARY
          echo "- **Git SHA:** \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- **Git Ref:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Usage" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo 'docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      # æž„å»ºå¤±è´¥æ—¶çš„é€šçŸ¥
      - name: Build failure notification
        if: failure()
        run: |
          echo "::error::Docker build failed - please check the build logs above for details"
          echo "::notice::Ensure your Dockerfile is properly configured and secrets are set correctly"