name: Tests

# 触发条件：推送和PR时运行测试
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 运行测试套件
      - name: Run tests
        id: tests
        run: |
          echo "::notice::Running test suite..."
          npm test
        env:
          NODE_ENV: test
          NODE_OPTIONS: --experimental-vm-modules
          # 数据库配置（根据项目需要调整）
          DATABASE_URL: ${{ secrets.TEST_DATABASE_URL || 'postgresql://test:test@localhost:5432/test_db' }}
          JWT_SECRET: test-secret-for-ci
          LOG_LEVEL: error

      # 上传测试覆盖率报告
      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage/
            test-results.xml
          retention-days: 30
          if-no-files-found: warn

      # 生成测试结果摘要
      - name: Generate test summary
        if: always()
        run: |
          echo "## Test Results 🧪" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.tests.outcome }}" == "success" ]; then
            echo "✅ All tests passed successfully!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Coverage Status" >> $GITHUB_STEP_SUMMARY
            echo "Coverage reports have been uploaded as artifacts and retained for 30 days." >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ Some tests failed. Please check the logs above for details." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
            echo "1. Review the failing test output above" >> $GITHUB_STEP_SUMMARY
            echo "2. Fix the failing tests locally" >> $GITHUB_STEP_SUMMARY
            echo "3. Run \`npm test\` locally to verify fixes" >> $GITHUB_STEP_SUMMARY
            echo "4. Commit and push your changes" >> $GITHUB_STEP_SUMMARY
          fi

      # 测试失败时的提示
      - name: Test failure notification
        if: failure()
        run: |
          echo "::error::Test suite failed - please check the test output for specific failure details"
          echo "::notice::Run 'npm test' locally to reproduce and debug the failing tests"